[application]

[web.app]

# HTML title tag content
title = "itf_patterns_rs"

# Additional CSS style files
style = []

[bundle]
identifier = "ITF Patterns Rs"
description = "Desktop app for randomizing ITF patterns"
publisher = "Oscar Aspelin"
icon = ["assets/icon/32x32.png", "assets/icon/16x16.png"]
